POST http://localhost:3003/website/salamat-trading/data
Content-Type: application/json

{
  "parts": [
    {
        "part":"profile",
        "version": 1
    },
    {
        "part":"about",
        "version": 1,
        "params": {"ok": true}
    },
    {
        "part":"social-links",
        "version": 1
    }
  ]
}