POST http://localhost:3003/website/salamattrading/data
Content-Type: application/json

{
  "parts": [
    {
        "part":"profile"
    },
    {
        "part":"about",
        "params": {"ok": true}
    },
    {
        "part":"social-links"
    }
  ]
}