POST http://localhost:3003/websites/salamat-trading/data
Content-Type: application/json

{
  "parts": [
    {
        "part":"profile",
        "version": 1
    },
    {
        "part":"about",
        "version": 1,
        "params": {"ok": true}
    },
    {
        "part":"social-links",
        "version": 1
    }
  ]
}

###

POST http://localhost:3003/websites/salamat-trading/pages
Content-Type: application/json

{
  "pageType": "ABOUT",
  "pageVariant": "ABOUT1",
  "slug": "about",
  "pageTitle": {
    "text": "About Us",
    "showAsHero": true
  }
}

###

POST http://localhost:3003/websites/
Content-Type: application/json

{
  "handle": "salamat-trading"
}

###

POST http://localhost:3003/websites/salamat-trading/pages
Content-Type: application/json

{
  "pageType": "CONTACT",
  "pageVariant": "CONTACT1",
  "slug": "contact",
  "pageTitle": {
    "text": "Contact Us",
    "showAsHero": false
  }
}